/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CountUpTimer;
import controller.ToggleButtons;
import javax.swing.JOptionPane;

/**
 *
 * @author Onur ŞAKRAKER
 */
public class OyunFrame extends javax.swing.JFrame {

    ToggleButtons tbut;
    CountUpTimer cut;

    /**
     * Creates new form Ekran
     */
    public OyunFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getRootPane().setDefaultButton(kutuUretButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kutuUretButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adetTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        yerlesimComboBox = new javax.swing.JComboBox();
        toggleButtonPanel = new javax.swing.JPanel();
        sureText = new javax.swing.JLabel();
        sureDeger = new javax.swing.JLabel();
        puanText = new javax.swing.JLabel();
        puanDeger = new javax.swing.JLabel();
        baslatButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 360));
        setPreferredSize(new java.awt.Dimension(400, 360));

        kutuUretButton.setText("KUTU ÜRET");
        kutuUretButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kutuUretButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Adet");

        adetTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adetTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Yerleşim");

        yerlesimComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FlowLayout", "GridLayout" }));

        toggleButtonPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black, java.awt.Color.white));

        javax.swing.GroupLayout toggleButtonPanelLayout = new javax.swing.GroupLayout(toggleButtonPanel);
        toggleButtonPanel.setLayout(toggleButtonPanelLayout);
        toggleButtonPanelLayout.setHorizontalGroup(
            toggleButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        toggleButtonPanelLayout.setVerticalGroup(
            toggleButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        sureText.setText("Süre:");

        sureDeger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sureDeger.setText("00:00:00");

        puanText.setText("Puan:");

        puanDeger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puanDeger.setText("0");

        baslatButton.setText("BAŞLAT");
        baslatButton.setEnabled(false);
        baslatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baslatButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(toggleButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(kutuUretButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(adetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(yerlesimComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(baslatButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sureText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sureDeger, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puanText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puanDeger, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kutuUretButton)
                    .addComponent(jLabel1)
                    .addComponent(adetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(yerlesimComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(puanText)
                    .addComponent(sureText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sureDeger)
                    .addComponent(puanDeger)
                    .addComponent(baslatButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adetTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adetTextFieldActionPerformed
        kutuUretButton.doClick();
    }//GEN-LAST:event_adetTextFieldActionPerformed

    private void kutuUretButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kutuUretButtonActionPerformed
       try {
            tbut = new ToggleButtons(Integer.parseInt(adetTextField.getText()), toggleButtonPanel,
                    yerlesimComboBox.getSelectedItem().toString());
            baslatButton.setEnabled(true);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Lütfen bir sayı girin.", "Uyarı", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_kutuUretButtonActionPerformed

    private void baslatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baslatButtonActionPerformed
        try {
            baslatButton.setEnabled(false);
            tbut.kutuGizle(ToggleButtons.buttons.length, ToggleButtons.buttons);
            new Thread(new CountUpTimer(sureDeger)).start();
        } catch (NullPointerException npe) {

        }
    }//GEN-LAST:event_baslatButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OyunFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OyunFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OyunFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OyunFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OyunFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adetTextField;
    private javax.swing.JButton baslatButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton kutuUretButton;
    public static javax.swing.JLabel puanDeger;
    private javax.swing.JLabel puanText;
    public static javax.swing.JLabel sureDeger;
    private javax.swing.JLabel sureText;
    private javax.swing.JPanel toggleButtonPanel;
    private javax.swing.JComboBox yerlesimComboBox;
    // End of variables declaration//GEN-END:variables
}
